const dataSet = {
  greetings: [
    "Hi",
    "Good morning",
    "Good evening",
    "How are you?",
    "I'm fine, thanks",
    "Thank you very much",
    "You're welcome",
    "Hey friend",
    "I missed you so much",
    "What's new?",
    "Nothing much",
    "Good night",
    "See you later",
    "Good bye"
  ],
  askingforhelp: [
    "I'm lost",
    "Can I help you?",
    "Where is the bathroom?",
    "Go straight then turn left",
    "Go straight then turn right",
    "I'm looking for John",
    "Hold on please",
    "How much is this?",
    "Excuse me"
  ],
  introducingyourself: [
    "Do you speak English?",
    "Just a little",
    "What's your name?",
    "My name is John",
    "Nice to meet you",
    "You're very kind",
    "Where are you from?",
    "I'm from America",
    "What do you do for a living?",
    "I work as a businessman",
    "How old are you?",
    "I am twenty years old"
  ],
  wishingothers: [
    "Good luck",
    "Happy birthday",
    "Happy new year",
    "Congratulations",
    "Say hi to John for me"
  ],
  solvingmisunderstanding: [
    "Sorry",
    "No problem",
    "Can you say it again?",
    "Can you speak slowly?",
    "I don't understand",
    "I don't know",
    "What is this?",
    "Don't worry"
  ],
  commonexpression: [
    "Good",
    "Bad",
    "Big",
    "Small",
    "Today",
    "Now",
    "Tomorrow",
    "Yesterday",
    "Do you like it?",
    "I really like it",
    "I'm hungry",
    "I'm thirsty",
    "In the morning",
    "In the evening",
    "In the night",
    "This",
    "That",
    "Here",
    "There",
    "Hurry up",
    "What time is it?",
    "It's 10am",
    "I love you",
    "I need a doctor",
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Six",
    "Seven",
    "Eight",
    "Nine",
    "Ten"
  ]
}

exports.dataSet = dataSet;
